# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hugo Initio"
license = "MIT"
licenselink = "https://github.com/miguelsimoni/hugo-initio/blob/master/LICENSE"
description = ""
homepage = "https://miguelsimoni.github.io/hugo-initio-site/"
tags = ["bootstrap","disqus","share this"]
features = []
min_version = "0.21"

[author]
  name = "Miguel Simoni"
  homepage = "https://miguelsimoni.github.io/"

# If porting an existing theme
[original]
  name = "Initio"
  author = "Sergey Pozhilov"
  homepage = "http://www.gettemplate.com/info/initio/"
  repo = "https://github.com/pozh/Initio"
